In [4]:
pip install gymnasium

   ---------------------------------------- 0.0/965.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/965.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/965.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/965.4 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/965.4 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/965.4 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/965.4 kB ? eta -:--:--
   ---------- ----------------------------- 262.1/965.4 kB ? eta -:--:--
   -------------------- ----------------- 524.3/965.4 kB 430.4 kB/s eta 0:00:02
   -------------------- ----------------- 524.3/965.4 kB 430.4 kB/s eta 0:00:02
   ------------------------------ ------- 786.4/965.4 kB 479.2 kB/s eta 0:00:01
   ------------------------------ ------- 786.4/965.4 kB 479.2 kB/s eta 0:00:01
   ------------------------------ ------- 786.4/965.4 kB 479.2 kB/s eta 0:00:01
   ---------------------


[notice] A new release of pip is available: 25.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import gymnasium as gym

In [6]:
env = gym.make('CartPole-v1')

In [7]:
env.action_space

Discrete(2)

In [8]:
env.action_space.n

2

In [11]:
[env.action_space.sample() for _ in range(10)]

[0, 0, 0, 1, 0, 1, 1, 1, 0, 0]

In [12]:
env.observation_space

Box([-4.8               -inf -0.41887903        -inf], [4.8               inf 0.41887903        inf], (4,), float32)

In [13]:
env.observation_space.shape

(4,)

In [23]:
env.reset(seed=100)

(array([ 0.03349816,  0.0096554 , -0.02111368, -0.04570484], dtype=float32),
 {})

In [24]:
env.step(0)

(array([ 0.03369127, -0.18515752, -0.02202777,  0.24024247], dtype=float32),
 1.0,
 False,
 False,
 {})

In [ ]:
env.step(1)

(array([ 0.03019356,  0.20563667, -0.01840905, -0.35737318], dtype=float32),
 1.0,
 False,
 False,
 {})

In [34]:
class Agent():
    def __init__(self):
        self.env = gym.make('CartPole-v1')
    def play(self, episodes=1):
        self.tr = list()
        for e in range(episodes):
            self.env.reset()
            for step in range(1, 100):
                a = self.env.action_space.sample()
                state, reward, done, truncated, info = self.env.step(a)
                if done:
                    self.tr.append(step) 
                    break

ra = Agent()
ra.play(30)
ra.tr

[14,
 9,
 26,
 53,
 12,
 19,
 16,
 24,
 17,
 27,
 19,
 26,
 25,
 13,
 16,
 31,
 46,
 12,
 47,
 17,
 55,
 27,
 22,
 18,
 26,
 21,
 22,
 26,
 18,
 14]

In [35]:
round(sum(ra.tr) / len(ra.tr), 2)

23.93

In [ ]:
import os  
import random  
import warnings  
import numpy as np  
import tensorflow as tf  
from tensorflow import keras  
from collections import deque  
from keras.layers import Dense  
from keras.models import Sequential

# Cell [17]
warnings.simplefilter('ignore')  
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  
os.environ['PYTHONHASHSEED'] = '0'

# Cell [18]
from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()
random.seed(100)
tf.random.set_seed(100)
opt = keras.optimizers.Adam(learning_rate=0.0001)



episode=1500 | treward=   8 | max= 109
Training completed!


In [2]:
agent.test(15)


Testing agent performance:
Episode 1: 8 steps | Episode 2: 10 steps | Episode 3: 10 steps | Episode 4: 9 steps | Episode 5: 9 steps | Episode 6: 8 steps | Episode 7: 10 steps | Episode 8: 10 steps | Episode 9: 10 steps | Episode 10: 9 steps | Episode 11: 10 steps | Episode 12: 9 steps | Episode 13: 10 steps | Episode 14: 10 steps | Episode 15: 10 steps | 
Average reward over 15 test episodes: 9.47


In [3]:
agent.epsilon

0.09997053357470892